name: Organizations  
on: [push]
jobs:
  deploy_source:
    name: Deploy API Using Lambda
    strategy:
      matrix:
        node-version: [12.x]
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true

      - name: /organizations get lambda deploy zip
        uses: postman-open-technologies/organizations@main
        with:
            args: zip -qq -r m-s-organizations-g.zip organizations/get/index.js node_modules
      - name: organization get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-organizations-g
            zip_file: m-s-organizations-g.zip
      - name: /organizations post lambda deploy zip
        uses: postman-open-technologies/organizations@main
        with:
            args: zip -qq -r m-s-organizations-po.zip organizations/post/index.js node_modules
      - name: organization get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-organizations-po
            zip_file: m-s-organizations-po.zip
      - name: /organizations/{organization_id} get lambda deploy zip
        uses: postman-open-technologies/organizations@main
        with:
            args: zip -qq -r m-s-organizations-organization-g.zip organizations/organization_id/get/index.js node_modules
      - name: organization get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-organizations-organization-g
            zip_file: m-s-organizations-organization-g.zip
      - name: /organizations/{organization_id} put lambda deploy zip
        uses: postman-open-technologies/organizations@main
        with:
            args: zip -qq -r m-s-organizations-organization-pu.zip organizations/organization_id/put/index.js node_modules
      - name: organization get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-organizations-organization-pu
            zip_file: m-s-organizations-organization-pu.zip
      - name: /organizations/{organization_id} delete lambda deploy zip
        uses: postman-open-technologies/organizations@main
        with:
            args: zip -qq -r m-s-organizations-organization-d.zip organizations/organization_id/delete/index.js node_modules
      - name: organization get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-organizations-organization-d
            zip_file: m-s-organizations-organization-d.zip          
      - name: /organizations/{organization_id}/tags get lambda deploy zip
        uses: postman-open-technologies/organizations@main
        with:
            args: zip -qq -r m-s-organizations-organization-tags-g.zip organizations/organization_id/tags/get/index.js node_modules
      - name: organizations get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-organizations-organization-tags-g
            zip_file: m-s-organizations-organization-tags-g.zip
      - name: /organizations/{organization_id}/tags post lambda deploy zip
        uses: postman-open-technologies/organizations@main
        with:
            args: zip -qq -r m-s-organizations-organization-tags-po.zip organizations/organization_id/tags/post/index.js node_modules
      - name: organizations get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-organizations-organization-tags-po
            zip_file: m-s-organizations-organization-tags-po.zip
      - name: /organizations/{organization_id}/tags/{tag_id} delete lambda deploy zip
        uses: postman-open-technologies/organizations@main
        with:
            args: zip -qq -r m-s-organizations-organization-tags-tag-d.zip organizations/organization_id/tags/tag_id/delete/index.js node_modules
      - name: organizations get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-organizations-organization-tags-tag-d
            zip_file: m-s-organizations-organization-tags-tag-d.zip            